title: Siddartha Jangid
logo: /assets/img/logo.png
description: This is just a basic example, to complete upgrad Excercise.
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
github:
  owner_name: Siddarth Jangid
  is_project_page: true
  owner_url: https://github.com/TheExorcist
  upgrad:
    git_excercise: https://github.com/TheExorcist/Course